### Root
GET http://localhost:3000



// 🌐🌐🌐 🌐🌐🌐 🌐🌐🌐 🌐🌐🌐 🌐🌐🌐 
### View all students
GET http://localhost:3000/api/students/




// ✅✅✅ ✅✅✅ ✅✅✅ ✅✅✅ ✅✅✅ 
### Create student
POST http://localhost:3000/api/students
Content-Type: application/json

{
  "first_name": "Jon",
  "last_name": "Do",
  "email":  "yb@email.com",
  "phone":  "1234567890",
  "gender": "Male"
}




// 🔎🔎🔎 🔎🔎🔎 🔎🔎🔎 🔎🔎🔎 🔎🔎🔎
### get student by id
GET http://localhost:3000/api/students/68461708b350ee8f23ebfd5e
Content-Type: application/json




// ❇️❇️❇️ ❇️❇️❇️ ❇️❇️❇️ ❇️❇️❇️ ❇️❇️❇️
### update student data
PUT http://localhost:3000/api/students/68461708b350ee8f23ebfd5e
Content-Type: application/json

{ 
  "last_name":  "Khan" 
}




// ❇️❇️❇️ ❇️❇️❇️ ❇️❇️❇️ ❇️❇️❇️ ❇️❇️❇️
### update student data
PUT http://localhost:3000/api/students/68461a4450c0605d331abfba
Content-Type: application/json

{
  "email":  "jon@email.com",
  "phone":  "5566"
}




// ❌❌❌ ❌❌❌ ❌❌❌ ❌❌❌ ❌❌❌
### delete student
DELETE http://localhost:3000/api/students/68461708b350ee8f23ebfd5e
Content-Type: application/json